image: node:4

stages:
    - test
    - package

test:
    tags:
        - docker-executor
    stage: test
    script:
        - echo "Testing Build Process"

package:
    tags:
        - docker-executor
    stage: package
    only:
        - /^sevedge_build*/
        - triggers
    script:
        - cd experimental/standalone/1nic
        - hash=`openssl dgst -r -sha512 azuredeploy.json | cut -d ' ' -f 1`
        - sed -i "s/INSERT_HASH_HERE/$hash/" verifyHash
    artifacts:
        name: f5-cloud-libs-$CI_BUILD_REF
        paths:
            - experimental/