image: node:4

stages:
    - test
    - package

test:
    tags:
        - docker-executor
    stage: test
    script:
        - python -B -m unittest discover -s build/test/lib -p "*Tests*.py"

package:
    tags:
        - docker-executor
    stage: package
    only:
        - /^build_hash*/
        - triggers
    script:
        - for f in `find supported -name 'azuredeploy.json'`; do
        -   echo "Template File $f Hash - `openssl dgst -r -sha512 $f | cut -d ' ' -f 1`" >> supportedTemplateHashes
        - done
    artifacts:
        name: f5-arm-build-$CI_BUILD_REF
        paths:
            - supported/