image: node:4

stages:
    - test
    - package

test:
    tags:
        - docker-executor
    stage: test
    script:
        - echo "Testing Build Process"

package:
    tags:
        - docker-executor
    stage: package
    only:
        - /^build_hash*/
        - triggers
    script:
        - 1nic_hash=`openssl dgst -r -sha512 /experimental/standalone/1nic/azuredeploy.json | cut -d ' ' -f 1`
        - 2nic_hash=`openssl dgst -r -sha512 /experimental/standalone/2nic_limited/azuredeploy.json | cut -d ' ' -f 1`
        - cluster_1nic_hash=`openssl dgst -r -sha512 /experimental/cluster/1nic/azuredeploy.json | cut -d ' ' -f 1`
        - sed -i "s/INSERT_1NIC_HASH_HERE/$1nic_hash/" templateHash
        - sed -i "s/INSERT_2NIC_HASH_HERE/$2nic_hash/" templateHash
        - sed -i "s/INSERT_CLUSTER_1NIC_HASH_HERE/$cluster_1nic_hash/" templateHash
    artifacts:
        name: f5-1nic-$CI_BUILD_REF
        paths:
            - /